esprit_famycity_homepage:
    path:     /
    defaults: { _controller: EspritFamycityBundle:Default:home }
Layoutt:
    path:     /layout
    defaults: { _controller: EspritFamycityBundle:Default:layoutA }
Login:
    path:     /login
    defaults: { _controller: EspritFamycityBundle:Default:loginA }

Reclamation:
    path:     /Reclamation
    defaults: { _controller: EspritFamycityBundle:Reclamation:ajoutP }

Reclamation2:
    path:     /MesReclamations
    defaults: { _controller: EspritFamycityBundle:Reclamation:Affichage }

delete_Reclmation:
    path:     /delete/{id}
    defaults: { _controller: EspritFamycityBundle:Reclamation:Suppression }

update_Reclamation:
    path:     /update/{id}
    defaults: { _controller: EspritFamycityBundle:Reclamation:Update  }

CreeCourse:
    path:     /CreeCourse
    defaults: { _controller: EspritFamycityBundle:Course:affichePageCreate }

savecourse:
    path:     /savecourse
    defaults: { _controller: EspritFamycityBundle:Course:ajoutCourse }

affichiercourse:
    path:     /affichiercourse
    defaults: { _controller: EspritFamycityBundle:Course:afficherCourse }


affichiercourseValid:
    path:     /affichiercourseValid
    defaults: { _controller: EspritFamycityBundle:Course:afficherCourseValider }

takecourse:
    path:     /takecourse/{idCourse}
    defaults: { _controller: EspritFamycityBundle:Course:takeCourse }


Stat:
    path:     /stat
    defaults: { _controller: EspritFamycityBundle:Stat:index  }


AfficheEvent:
    path:     /showEvent
    defaults: { _controller: EspritFamycityBundle:Event:findEventDQL }

TimeLine:
    path:     /Acceuil
    defaults: { _controller: EspritFamycityBundle:TimeLinePosts:timeLine }
likePost:
    path:     /likePost/{idPost}
    defaults: {_controller: EspritFamycityBundle:TimeLinePosts:likePost}
CommentPost:
    path:     /Comment/{idPost}
    defaults: {_controller: EspritFamycityBundle:TimeLinePosts:commentPubTimeLine}
getSinglePost:
    path:     /singlePost/{idPost}
    defaults: {_controller: EspritFamycityBundle:TimeLinePosts:getPub}
deleteSinglePost:
    path:     /deleteSinglePost/{idPost}
    defaults: {_controller: EspritFamycityBundle:TimeLinePosts:deletePub}
editSinglePost:
    path: /editSinglePost/{idPost}
    defaults: {_controller: EspritFamycityBundle:TimeLinePosts:editSinglePost}
editSinglePostShow:
    path: /editSinglePostFStep/{idPost}
    defaults: {_controller: EspritFamycityBundle:TimeLinePosts:loadPubToEdit}
