esprit_famycity_homepage:
    path:     /
    defaults: { _controller: EspritFamycityBundle:Default:home }
Layoutt:
    path:     /layout
    defaults: { _controller: EspritFamycityBundle:Default:layoutA }
Login:
    path:     /loginA
    defaults: { _controller: EspritFamycityBundle:Default:loginA }

Reclamation:
    path:     /Reclamation
    defaults: { _controller: EspritFamycityBundle:Reclamation:ajoutP }

Reclamation2:
    path:     /MesReclamations
    defaults: { _controller: EspritFamycityBundle:Reclamation:Affichage }

delete_Reclmation:
    path:     /delete/{id}
    defaults: { _controller: EspritFamycityBundle:Reclamation:Suppression }

update_Reclamation:
    path:     /update/{id}
    defaults: { _controller: EspritFamycityBundle:Reclamation:Update  }

CreeCourse:
    path:     /CreeCourse
    defaults: { _controller: EspritFamycityBundle:Course:affichePageCreate }

savecourse:
    path:     /savecourse
    defaults: { _controller: EspritFamycityBundle:Course:ajoutCourse }



Stat:
    path:     /stat
    defaults: { _controller: EspritFamycityBundle:Stat:index  }

AjoutEvent:
    path:     /addEvent
    defaults: { _controller: EspritFamycityBundle:Event:addEvent }

AjoutEvents:
        path:     /addEvents
        defaults: { _controller: EspritFamycityBundle:Event:addEvents }

AfficheEvent:
    path:     /showEvent
    defaults: { _controller: EspritFamycityBundle:Event:findEventDQL }

DeleteEvent:
        path:   /showEvent
        defaults: { _controller: EspritFamycityBundle:Event:findEventDQL }

UpdateEvent:
    path:     /showEvent
    defaults: { _controller: EspritFamycityBundle:Event:findEventDQL }

persistEvent:
    path:     /persistEvent
    defaults: { _controller: EspritFamycityBundle:Event:persistEvent }